apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-liveness-readiness-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-liveness-readiness-deployment
  template:
    metadata:
      labels:
        app: api-liveness-readiness-deployment
    spec:
      containers:
      - name: api-liveness-readiness
        image: [NOME_DA_IMAGEM_GERADA]
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: DATABASE_HOST
          value: [WSL_ENDPOINT]
        - name: DATABASE_USERNAME
          value: [DATABASE_USERNAME]
        - name: DATABASE_PASSWORD
          value: [DATABASE_PASSWORD]
        - name: DATABASE_NAME
          value: [DATABASE_NAME]

---

apiVersion: v1
kind: Service
metadata:
  name: api-liveness-readiness-service
spec:
  selector:
    name: api-liveness-readiness-deployment
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP